### ISSUE TITLE
Could not download app notestutorial

### ISSUE THREAD

**Issue by kamalkech** [nextcloud/app-tutorial#6]
not compatible with last version ??

**Comment by juliushaertl** [comment]
This is now fixed with the current master branch being compatible to 17 (but should also work on 15/16)

**Comment by brjhaverkamp** [comment]
I get the same message in the nextcloud frontend -> settings-> apps.
When I try to enable the app, I get an orange banner with the words "Could not download app notestutorial"

**Comment by robbieh** [comment]
The name of the app in `appinfo/info.xml` needs to match the name of the app directory. Renaming the directory fixed this problem for me.

**Comment by brjhaverkamp** [comment]
Thanks for the pointer, robbieh,
I think you meant the id of the app in appinfo/info.xml, right?
I found the following in info.xml
```
    <id>notestutorial</id>
    <name>Notes Tutorial</name>

```
so I renamed the folder from app-tutorial to notestutorial. 
After that I could enable the app.

Looking back, if I had read the Readme better, and used:
`git clone https://github.com/nextcloud/app-tutorial.git notestutorial`
instead of 
`git clone https://github.com/nextcloud/app-tutorial.git`
this problem wouldn't have come up. RTFM... :-)
My suggestion would be to add an extra remark to the readme for people who overlooked this just like me.

Regards,

Bert
